ytitle: UH Jewels
description: Market place for shell jewelry
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman
gem:
  - jekyll-mentions
repository: https://github.com/UH-Jewels/Uh-jewels.github.io
